### ISSUE TITLE
Suggest: allow relay or direct transmitter for KPS

### ISSUE THREAD

**Issue by AssidiousBlue** [IO5/KspConstellations#2]
Just launched a satellite up for kerbin positioning system prototype thinking that a 15G relay is able to meet criteria of a 15G  
mtransmit;
(RA-15)
Sadly it does not meet the criteria.
I believe this is defined by https://github.com/IO5/KspConstellations/blob/b2621d070248d0e6ac411d5838620ee1d0fa5395/KPS/KPSPrototype.cfg#L120

**Comment by IO5** [comment]
Yeah I agree this is confusing to the player. Gameplay-wise relay antenna is the same as transmit antenna, just with extra functionality. 

I made a PR to CC that adds EITHER option https://github.com/KSP-RO/ContractConfigurator/pull/41 so I'd prefer to wait until it's merged before I fix it on my end.

Also, I'm out of town until the end of the month and I don't have access to my PC, so this has to wait until I'm back anyway.

**Comment by IO5** [comment]
Added in version 0.6

**Comment by IO5** [comment]
well, nevermind I missed some contracts, will fix in 0.8
