### ISSUE TITLE
The moon relay script seem to loop

### ISSUE THREAD

**Issue by Tutul-** [IO5/KspConstellations#5]
I've finished the contract for "The Mun" (btw it take the "The" of the name) but the contract is proposed again. After checking the cfg file, there isn't any conditions that seem to avoid proposing multiple time for the same moon

**Comment by IO5** [comment]
Well this bit:

```
	REQUIREMENT
	{
		name = NotEstablished
		type = ValidVessel

		vessel = @/relay
		invertRequirement = true
	}

	PARAMETER
	{
		name = VesselParameterGroup
		type = VesselParameterGroup

		define = @/relay
```

is responsible for preventing repeated contracts for the same body. So unless the vessel got deleted/destroyed it shouldn't propose the same contract twice. Maybe the vessel was not saved by the contract configurator? Could you ctrl-f your savefile for `PersistentDataStore` and paste the whole node?

**Comment by Tutul-** [comment]
SCENARIO
	{
		name = PersistentDataStore
		scene = 7, 8, 5
		DATA
		{
			Constellations_Sat_Counter = Double:11
		}
	}

**Comment by IO5** [comment]
ah sorry, one node below that `SCENARIO` `ContractVesselTracker`

**Comment by Tutul-** [comment]
SCENARIO
	{
		name = ContractVesselTracker
		scene = 7, 8, 5
	}

**Comment by IO5** [comment]
Well, it's supposed to look like this:

```
	SCENARIO
	{
		name = ContractVesselTracker
		scene = 7, 8, 5
		VESSEL
		{
			key = The Mun Relay A
			id = c020203e-6d10-49f9-b7a1-0909b3be1d99
			hash = 395262460
		}
	}
```

on my non-dev savefile I have few dozens of vessels there, seeing it completely empty is suspicious. Might be a bug in the Contract Configurator. 

Could you repeat the contract (alt+12 set orbit for quick completion) and check if it gets added? And if not, could you upload your `Player.log` (`%userprofile%\AppData\LocalLow\SQUAD\Kerbal Space Program`) somewhere?

**Comment by Tutul-** [comment]
Ok I think I know what is the main trouble then.
Did wanted to try a better sat contract pack but it's partly incompatible with one of my mods (realAntenna).
So when all the requirement where ok, I did force the contract to be complete but that had the effect to skip the part where the vessel data is saved...

But I might provide support for realAntenna in an other pull request if I get the time to think on how to add that for the relay strength condition (if you are ok with that ofc)

**Comment by IO5** [comment]
> I did force the contract to be complete

Yeah, that's the downside of this approach: user can't force contract to complete. It can't be helped unfortunately, because the *FollowUp contracts (and unreleased station-keep contracts) use the vessel from the original contract for their parameters 😞. I probably should add that to FAQ.

> But I might provide support for realAntenna in an other pull request if I get the time to think on how to add that for the relay strength condition (if you are ok with that ofc)

Sure. I'm not too familiar with realAntenna, but from what I gather it might require C# plugin for the Contract Configurator.
